# Site wide configuration

title: Panda的博客
locale: zh_CN
description: 专业打怪兽，业余写代码。为了世界和平而战_(·ω·√∠)_
logo: panda.png
search: true
url: http://leewenlin.com/blog
#url: http://localhost:4000/blog
baseurl: /blog

# Jekyll configuration

permalink:   /:categories/:title.html
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: leewenlin
  avatar: panda.png
  email: 412443296@qq.com
  disqus-shortname: #"leewenlin"
  duoshuo: leewenlin
  twitter: #username
  facebook: leewenlin.panda
  github: leewenlin
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: leewenlin
  instagram: #username
  flickr: #username
  tumblr: #username
  weibo: #1743643777
  google:
    plus: #username
    analytics: UA-60227111-1
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
